Repository aisingapore/PeekingDuck, pull requests merged in 2021-08, with the labels that each got.

#362 Draw nodes docstrings
  docs/_templates/class.rst
  docs/source/io_draw_nodes.md
  peekingduck/pipeline/nodes/draw/__init__.py
  peekingduck/pipeline/nodes/draw/bbox.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
  peekingduck/pipeline/nodes/draw/image_processor.py
  peekingduck/pipeline/nodes/draw/legend.py
  peekingduck/pipeline/nodes/draw/poses.py
  peekingduck/pipeline/nodes/draw/tag.py
  peekingduck/pipeline/nodes/draw/zones.py
Labels: documentation

#378 test(yolo): fix unit test failing on windows
  tests/conftest.py
  tests/pipeline/nodes/model/yolov4/test_yolo.py
Labels: bug, cicd

#384 Draw tests
  peekingduck/pipeline/nodes/draw/utils/bbox.py
  tests/pipeline/nodes/draw/test_bbox.py
  tests/pipeline/nodes/draw/test_btm_midpoint.py
  tests/pipeline/nodes/draw/test_group_bbox_and_tag.py
  tests/pipeline/nodes/draw/test_image_processor.py
  tests/pipeline/nodes/draw/test_legend.py
  tests/pipeline/nodes/draw/test_poses.py
  tests/pipeline/nodes/draw/test_tag.py
  tests/pipeline/nodes/draw/test_zones.py
Labels: cicd, testing

#386 Changed 'heuristic' nodes to 'dabble' and updated colour scheme of diagrams
  README.md
  diagrams/node_types.drawio.svg
  diagrams/yolo_demo.drawio.svg
  docs/source/introduction/01_introduction.md
Labels: documentation

#363 additional references
  README.md
  docs/source/introduction/01_introduction.md
Labels: documentation

#393 engine(requirements): change sphinx_requirements to cicd_requirements…
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
  .github/workflows/publish_pypi.yml
  cicd_requirements.txt
  requirements.txt
  sphinx_requirements.txt
Labels: cicd, dependencies

#394 docs(requirements): update requirements in readthedocs.yaml
  .readthedocs.yaml
Labels: cicd, dependencies

#397 added bibliography section
  README.md
  docs/source/index.rst
  docs/source/introduction/01_introduction.md
  docs/source/introduction/02_bibliography.md
Labels: documentation

#383 Threshold error messages
  peekingduck/configs/model/yolo.yml
  peekingduck/pipeline/nodes/input/live.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_model.py
  peekingduck/pipeline/nodes/model/hrnet.py
  peekingduck/pipeline/nodes/model/hrnetv1/hrnet_model.py
  peekingduck/pipeline/nodes/model/posenetv1/posenet_model.py
  peekingduck/pipeline/nodes/model/yolov4/yolo_model.py
  peekingduck/pipeline/nodes/output/csv_writer.py
  peekingduck/pipeline/nodes/output/media_writer.py
Labels: enhancement

#396 docs(packaging): updated broken links and removed deprecated docs
  README.md
  docs/source/getting_started/01_installation.md
  docs/source/getting_started/02_configure_pkdk.md
  docs/source/introduction/01_introduction.md
  docs/source/io_draw_nodes.md
  docs/source/node_data_mapping.md
Labels: documentation

#400 Fix rtd links
  README.md
Labels: bug, documentation

#389 test(docs): check markdowns and htmls for broken links
  .github/workflows/pre_merge_ci.yml
  cicd_requirements.txt
  scripts/check_links.py
Labels: documentation, testing

#406 test(cicd): added the broken link checks in pre and post merge GitHub workflow
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
Labels: cicd

#404 added docs for python api
  README.md
  docs/source/conf.py
  docs/source/getting_started/04_python_mode.md
  docs/source/getting_started/05_benchmarks.rst
Labels: documentation

#403 Fix pypi gifs
  README.md
  setup.cfg
Labels: documentation

#410 Test model setup
  peekingduck/pipeline/nodes/draw/utils/zone.py
  peekingduck/pipeline/nodes/model/yolov4/yolo_files/utils.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
  tests/pipeline/nodes/model/yolov4/test_yolo.py
Labels: testing

#412 Revert previous commit to change yolo test fixture
  .github/workflows/post_merge_checks.yml
  tests/conftest.py
  tests/pipeline/nodes/model/yolov4/test_yolo.py
Labels: bug, cicd, testing

#414 docs (API ref): removed utils from being built
  docs/source/conf.py
Labels: documentation

#415 docs (node_configs): Updated guide
  README.md
  docs/source/getting_started/02_configure_pkdk.md
Labels: documentation

#418 node (template): updated template to use kwargs
  peekingduck/pipeline/nodes/node_template.py
Labels: node, engine

#413 Update custom nodes guide
  docs/source/getting_started/03_custom_nodes.md
  peekingduck/cli.py
Labels: documentation

#421 Fps results
  docs/source/getting_started/05_benchmarks.rst
Labels: documentation

#426 Fix RTD guides after Testing
  docs/source/getting_started/01_installation.md
  docs/source/getting_started/02_configure_pkdk.md
  docs/source/getting_started/03_custom_nodes.md
  docs/source/getting_started/04_python_mode.md
Labels: documentation

#424 dependencies(setup.cfg): update shapely version to 1.7.1 same as requirement.txt
  requirements.txt
  setup.cfg
Labels: dependencies

#430 Fix linux threading
  peekingduck/configs/input/live.yml
  peekingduck/pipeline/nodes/input/live.py
Labels: bug

#431 Fix zonecounting docs
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/social_distancing.md
  docs/source/use_cases/zone_counting.md
Labels: documentation

#440 fix(model): remove v3 and v3tiny in the comments for model type
  peekingduck/pipeline/nodes/model/yolo.py
Labels: documentation

#441 Revamp RTD stylesheet
  README.md
  cicd_requirements.txt
  docs/source/_static/css/pkdk.css
  docs/source/conf.py
  docs/source/index.md
  docs/source/master.rst
  docs/source/resources/01_benchmarks.rst
  docs/source/resources/02_model_indices.rst
  peekingduck/pipeline/nodes/model/efficientdet.py
Labels: documentation
