Repository aisingapore/PeekingDuck, pull requests merged in 2021-07, with the labels that each got.

#285 Fix gifs
  docs/source/introduction/README.md
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/social_distancing.md
  docs/source/use_cases/zone_counting.md
Labels: bug, documentation

#261 245 test hrnet
  tests/pipeline/nodes/model/hrnetv1/__init__.py
  tests/pipeline/nodes/model/hrnetv1/test_detector.py
  tests/pipeline/nodes/model/hrnetv1/test_hrnet.py
  tests/pipeline/nodes/model/hrnetv1/test_hrnet.yml
  tests/pipeline/nodes/model/hrnetv1/test_postprocessing.py
  tests/pipeline/nodes/model/hrnetv1/test_preprocessing.py
Labels: testing

#311 Revamped front page of docs for RTD
  docs/source/getting_started/01_installation.md
  docs/source/getting_started/02_configure_pkdk.md
  docs/source/getting_started/03_custom_nodes.md
  docs/source/index.rst
  docs/source/introduction/README.md
  docs/source/introduction/introduction.md
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/social_distancing.md
  docs/source/use_cases/zone_counting.md
Labels: documentation

#323 feat(docs): Refactor Posenet docs
  docs/_templates/class.rst
  docs/source/conf.py
  docs/source/glossary.rst
  peekingduck/pipeline/nodes/model/posenet.py
Labels: documentation

#339 docs(nodes): refactor doc strings for read the docs
  docs/_templates/class.rst
  peekingduck/pipeline/nodes/input/live.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/pipeline/nodes/node.py
  peekingduck/pipeline/pipeline.py
Labels: documentation

#324 FPS Evaluation
  peekingduck/configs/draw/fps.yml
  peekingduck/configs/heuristic/fps.yml
  peekingduck/pipeline/nodes/draw/fps.py
  peekingduck/pipeline/nodes/heuristic/fps.py
  tests/pipeline/nodes/heuristic/test_fps.py
Labels: enhancement

#348 Added benchmark page
  docs/source/getting_started/04_benchmarks.rst
  docs/source/index.rst
  docs/source/introduction/01_introduction.md
Labels: documentation

#349 Removed docs of model submodules
  docs/source/conf.py
Labels: documentation

#345 RTD revamp: HRNet, heuristics nodes doc strings
  docs/_templates/class.rst
  peekingduck/pipeline/nodes/heuristic/bbox_count.py
  peekingduck/pipeline/nodes/heuristic/bbox_to_btm_midpoint.py
  peekingduck/pipeline/nodes/heuristic/fps.py
  peekingduck/pipeline/nodes/heuristic/zone_count.py
  peekingduck/pipeline/nodes/model/hrnet.py
Labels: documentation

#353 fix(refactor): changed fps logging to true
  peekingduck/configs/heuristic/fps.yml
Labels: enhancement
