Repository aisingapore/PeekingDuck, pull requests merged in 2021-11, with the labels that each got.

#520 Support CLI parameter --log_level (and --config_path)
  __main__.py
  peekingduck/__init__.py
  peekingduck/cli.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/utils/logger.py
  tests/cli/test_cli.py
Labels: enhancement

#523 432 Threading
  docs/Makefile
  peekingduck/configs/input/live.yml
  peekingduck/configs/input/recorded.yml
  peekingduck/pipeline/nodes/input/live.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/pipeline/nodes/input/utils/read.py
  peekingduck/pipeline/nodes/node.py
  peekingduck/runner.py
  tests/pipeline/nodes/input/test_input_threading.py
  tests/pipeline/nodes/input/test_recorded.py
Labels: enhancement

#532 Fix post merge test failures
  peekingduck/pipeline/nodes/input/utils/read.py
  tests/pipeline/nodes/input/test_input_threading.py
Labels: bug

#527 Add CLI parameter --log_level
  __main__.py
  peekingduck/cli.py
  peekingduck/utils/logger.py
  tests/cli/test_cli.py
Labels: enhancement

#534 Fixed sphinx error on Windows when building html
  docs/make.bat
Labels: bug

#536 CI/CD tests for `import peekingduck` Python API mode
  .github/workflows/daily_drift_checks.yml
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
  pyproject.toml
  scripts/run_tests.sh
  scripts/update_version.sh
  tests/api/__init__.py
  tests/api/test_api.py
Labels: cicd

#539 cicd: pin pypi-publish version to v1.4.2
  .github/workflows/publish_pypi.yml
  .github/workflows/publish_skip_testpypi.yml
Labels: cicd

#541 Rename misleading "Python API" feature as "Import PeekingDuck as a Module"
  .github/workflows/daily_drift_checks.yml
  .github/workflows/post_merge_checks.yml
  README.md
  docs/source/getting_started/04_import_peekingduck.md
  docs/source/getting_started/index.rst
  docs/source/index.md
  pyproject.toml
  scripts/run_tests.sh
  tests/module_import/__init__.py
  tests/module_import/test_module_import.py
Labels: documentation
