Repository aisingapore/PeekingDuck, pull requests merged in 2021-12, with the labels that each got.

#549 Fix 28 spelling errors in code, comments and docs
  docs/source/getting_started/01_installation.md
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/social_distancing.md
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/dabble/zoningv1/zone.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/utils/general.py
  peekingduck/pipeline/nodes/input/utils/preprocess.py
  peekingduck/pipeline/nodes/model/efficientdet.py
  peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/utils/model_process.py
  peekingduck/pipeline/nodes/model/posenet.py
  peekingduck/pipeline/nodes/model/posenetv1/posenet_files/preprocessing.py
  peekingduck/pipeline/nodes/model/yolov4/yolo_files/models.py
  peekingduck/utils/requirement_checker.py
  peekingduck/weights_utils/downloader.py
  tests/conftest.py
  tests/pipeline/nodes/draw/test_btm_midpoint.py
  tests/pipeline/nodes/draw/test_legend.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
Labels: documentation

#535 New model node: MoveNet
  docs/source/conf.py
  docs/source/resources/01b_pose_estimation.rst
  docs/source/resources/02_bibliography.rst
  peekingduck/configs/model/movenet.yml
  peekingduck/pipeline/nodes/model/movenet.py
  peekingduck/pipeline/nodes/model/movenetv1/__init__.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_files/__init__.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_files/predictor.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_model.py
  tests/pipeline/nodes/model/movenetv1/__init__.py
  tests/pipeline/nodes/model/movenetv1/test_groundtruth.yml
  tests/pipeline/nodes/model/movenetv1/test_movenet.py
  tests/pipeline/nodes/model/movenetv1/test_movenet.yml
  tests/pipeline/nodes/model/movenetv1/test_predictor.py
Labels: enhancement

#555 Issue: Fixed failed test for movenet in post merge
  peekingduck/pipeline/nodes/model/movenetv1/movenet_files/predictor.py
  tests/pipeline/nodes/model/movenetv1/test_movenet.py
Labels: bug, testing

#553 Multi-Object Tracking
  docs/source/getting_started/01_installation.md
  docs/source/index.md
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/index.rst
  docs/source/use_cases/multi_object_tracking.md
  docs/source/use_cases/social_distancing.md
  images/readme/vehicles_tracking.gif
  peekingduck/configs/dabble/tracking.yml
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/dabble/tracking.py
  peekingduck/pipeline/nodes/dabble/utils/load_tracker.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/__init__.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/__init__.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/iou_tracker.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/misc.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/track.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/tracker.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracker/utils.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/iou_tracking.py
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/opencv_tracking.py
  peekingduck/pipeline/nodes/dabble/zoningv1/zone.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/utils/general.py
  peekingduck/pipeline/nodes/input/utils/preprocess.py
  peekingduck/pipeline/nodes/model/efficientdet.py
  peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/utils/model_process.py
  peekingduck/pipeline/nodes/model/posenet.py
  peekingduck/pipeline/nodes/model/posenetv1/posenet_files/preprocessing.py
  peekingduck/pipeline/nodes/model/yolov4/yolo_files/models.py
  peekingduck/utils/requirement_checker.py
  peekingduck/weights_utils/downloader.py
  requirements.txt
  tests/conftest.py
  tests/pipeline/nodes/dabble/test_tracking.py
  tests/pipeline/nodes/draw/test_btm_midpoint.py
  tests/pipeline/nodes/draw/test_legend.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
  tests/use_cases/systest_object_tracking.yml
  use_cases/object_tracking.yml
Labels: enhancement

#547 Add configurable options to improve `output.screen` node
  peekingduck/configs/output/screen.yml
  peekingduck/pipeline/nodes/output/screen.py
Labels: enhancement

#569 docs: fix directory structure in build custom nodes tutorial
  docs/source/getting_started/03_custom_nodes.md
Labels: documentation
