Repository aisingapore/PeekingDuck, pull requests merged in 2022-09, with the labels that each got.

#702 Node: Hugging Face Hub models
  cicd_requirements.txt
  docs/source/conf.py
  docs/source/resources/01a_object_detection.rst
  lint_requirements.txt
  peekingduck/cli.py
  peekingduck/commands/model_hub/__init__.py
  peekingduck/commands/model_hub/huggingface.py
  peekingduck/configs/model/huggingface_hub.yml
  peekingduck/declarative_loader.py
  peekingduck/optional_requirements.txt
  peekingduck/pipeline/nodes/base.py
  peekingduck/pipeline/nodes/model/huggingface_hub.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/__init__.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/api_utils.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/huggingface_hub_model.py
  requirements.txt
  setup.cfg
  tests/pipeline/nodes/base/test_weights_downloader_mixin.py
  tests/pipeline/nodes/model/huggingface_hubv1/__init__.py
  tests/pipeline/nodes/model/huggingface_hubv1/test_huggingface_hub.py
  tests/pipeline/nodes/model/huggingface_hubv1/test_huggingface_hub_model.py
Labels: enhancement

#703 Cicd: refer other requirement file
  .github/workflows/daily_drift_checks.yml
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
  .github/workflows/publish_pypi.yml
  .readthedocs.yaml
  lint_requirements.txt
  requirements_cicd.txt
  requirements_lint.txt
  tests/utils/test_requirement_checker.py
Labels: cicd

#704 Feat: huggingface segmentation models
  peekingduck/configs/model/huggingface_hub.yml
  peekingduck/pipeline/nodes/model/huggingface_hub.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/adaptors/__init__.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/adaptors/base.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/adaptors/instance_segmenter.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/adaptors/object_detector.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/adaptors/panoptic_segmenter.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/api_utils.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/models/__init__.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/models/base.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/models/instance_segmentation.py
  peekingduck/pipeline/nodes/model/huggingface_hubv1/models/object_detection.py
  tests/pipeline/nodes/model/huggingface_hubv1/test_huggingface_hub.py
  tests/pipeline/nodes/model/huggingface_hubv1/test_huggingface_hub_model.py
Labels: enhancement

#707 bug fix: mirror_image not working when threading is False
  peekingduck/pipeline/nodes/input/utils/read.py
Labels: bug

#708 bug fix: VideoThread.__del__ crashes on python 3.7
  peekingduck/pipeline/nodes/input/utils/read.py
Labels: bug
