Repository aisingapore/PeekingDuck, pull requests merged in 2022-07, with the labels that each got.

#668 Feat optimized models
  docs/source/assets/charts/tensorrt_agx_movenet_fps.png
  docs/source/assets/charts/tensorrt_agx_yolox_fps.png
  docs/source/assets/charts/tensorrt_nx_movenet_fps.png
  docs/source/assets/charts/tensorrt_nx_yolox_fps.png
  docs/source/edge_ai/index.rst
  docs/source/master.rst
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  peekingduck/configs/model/movenet.yml
  peekingduck/configs/model/yolox.yml
  peekingduck/pipeline/nodes/base.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_files/predictor.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_model.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/detector.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/trt_model.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_model.py
  scripts/benchmarks/pytorch/run_yolox_large_multi.yml
  scripts/benchmarks/pytorch/run_yolox_large_single.yml
  scripts/benchmarks/pytorch/run_yolox_medium_multi.yml
  scripts/benchmarks/pytorch/run_yolox_medium_single.yml
  scripts/benchmarks/pytorch/run_yolox_small_multi.yml
  scripts/benchmarks/pytorch/run_yolox_small_single.yml
  scripts/benchmarks/pytorch/run_yolox_tiny_multi.yml
  scripts/benchmarks/pytorch/run_yolox_tiny_single.yml
  scripts/benchmarks/run_benchmarks.sh
  scripts/benchmarks/tensorflow/run_multipose_lightning.yml
  scripts/benchmarks/tensorflow/run_singlepose_lightning.yml
  scripts/benchmarks/tensorflow/run_singlepose_thunder.yml
  scripts/benchmarks/tensorrt/run_multipose_lightning.yml
  scripts/benchmarks/tensorrt/run_singlepose_lightning.yml
  scripts/benchmarks/tensorrt/run_singlepose_thunder.yml
  scripts/benchmarks/tensorrt/run_yolox_large_multi.yml
  scripts/benchmarks/tensorrt/run_yolox_large_single.yml
  scripts/benchmarks/tensorrt/run_yolox_medium_multi.yml
  scripts/benchmarks/tensorrt/run_yolox_medium_single.yml
  scripts/benchmarks/tensorrt/run_yolox_small_multi.yml
  scripts/benchmarks/tensorrt/run_yolox_small_single.yml
  scripts/benchmarks/tensorrt/run_yolox_tiny_multi.yml
  scripts/benchmarks/tensorrt/run_yolox_tiny_single.yml
  scripts/converters/compute_weights_checksum.py
  scripts/converters/pytorch_to_onnx/convert_yolox_to_onnx.py
  scripts/converters/tensorflow_to_trt/convert_movenet_to_trt.py
Labels: enhancement

#667 node: Mask-RCNN code for instance segmentation
  peekingduck/configs/model/mask_rcnn.yml
  peekingduck/pipeline/nodes/model/mask_rcnn.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/LICENSE
  peekingduck/pipeline/nodes/model/mask_rcnnv1/__init__.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/__init__.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/backbones/__init__.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/backbones/resnet.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/__init__.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/anchor_utils.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/backbone_utils.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/detection_utils.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/faster_rcnn.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/generalized_rcnn.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/image_list.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/mask_rcnn.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/roi_heads.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/rpn.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detection/transform.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/detector.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/__init__.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/boxes.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/feature_pyramid_network.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/misc.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/poolers.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_files/ops/roi_align.py
  peekingduck/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_model.py
  peekingduck/pipeline/nodes/model/master_map.yml
  peekingduck/utils/create_node_helper.py
  tests/pipeline/nodes/model/mask_rcnnv1/__init__.py
  tests/pipeline/nodes/model/mask_rcnnv1/mask_rcnn_gt_masks.npz
  tests/pipeline/nodes/model/mask_rcnnv1/test_groundtruth.yml
  tests/pipeline/nodes/model/mask_rcnnv1/test_mask_rcnn.py
Labels: enhancement, testing

#669 fix: display window not initializing to the correct aspect ratio and size
  peekingduck/configs/output/screen.yml
  peekingduck/pipeline/nodes/output/screen.py
Labels: bug, enhancement

#671 Docs: Documentation for Mask-RCNN
  docs/source/conf.py
  docs/source/glossary.rst
  docs/source/include/data_type.rst
  docs/source/index.rst
  docs/source/resources/01e_instance_segmentation.rst
  docs/source/resources/02_bibliography.rst
  docs/source/resources/index.rst
  peekingduck/pipeline/nodes/model/mask_rcnn.py
Labels: documentation

#648 Feat: PeekingDuck Runtime Viewer
  __main__.py
  docs/source/assets/diagrams/viewer_cat_computer.png
  docs/source/assets/tutorials/viewer_main.png
  docs/source/assets/tutorials/viewer_playlist.png
  docs/source/ecosystem/index.rst
  docs/source/ecosystem/viewer.rst
  docs/source/master.rst
  docs/source/tutorials/01_hello_cv.rst
  peekingduck/cli.py
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/input/utils/read.py
  peekingduck/pipeline/nodes/output/screen.py
  peekingduck/viewer/PeekingDuckLogo.png
  peekingduck/viewer/__init__.py
  peekingduck/viewer/playlist.py
  peekingduck/viewer/single_column_view.py
  peekingduck/viewer/viewer.py
  peekingduck/viewer/viewer_gui.py
  peekingduck/viewer/viewer_utils.py
  tests/cli/test_cli.py
  tests/cli/test_cli_create_node.py
  tests/conftest.py
  tests/module_import/test_module_import.py
  tests/pipeline/nodes/input/test_input_threading.py
Labels: enhancement

#678 Fix setup.cfg, add setup.py
  setup.cfg
  setup.py
Labels: bug
