Repository aisingapore/PeekingDuck, pull requests merged in 2022-01, with the labels that each got.

#572 fix: use opencv-contrib-python so opencv tracker works
  peekingduck/pipeline/nodes/dabble/utils/tracking_files/opencv_tracking.py
  requirements.txt
  setup.cfg
Labels: bug, dependencies

#571 Feature: `--num_iter` CLI option to stop pipeline after `num_iter` runs
  __main__.py
  peekingduck/cli.py
  peekingduck/runner.py
  tests/cli/test_cli.py
  tests/runner/test_runner.py
Labels: enhancement

#560 Create new category of `preprocess` nodes
  README.md
  diagrams/node_types.drawio.svg
  diagrams/yolo_demo.drawio.svg
  docs/source/index.md
  docs/source/master.rst
  peekingduck/configs/preprocess/brightness.yml
  peekingduck/configs/preprocess/contrast.yml
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/preprocess/__init__.py
  peekingduck/pipeline/nodes/preprocess/brightness.py
  peekingduck/pipeline/nodes/preprocess/contrast.py
  tests/pipeline/nodes/draw/test_image_processor.py
  tests/pipeline/nodes/preprocess/test_brightness.py
  tests/pipeline/nodes/preprocess/test_contrast.py
Labels: enhancement

#566 cicd: add timeout to check links
  scripts/check_links.py
Labels: cicd

#573 Add clean: to makefile for 'make clean'
  docs/Makefile
Labels: documentation

#564 Cicd windows post merge
  .github/workflows/post_merge_checks.yml
  peekingduck/pipeline/nodes/model/movenet.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_model.py
  scripts/run_tests.sh
  tests/conftest.py
  tests/pipeline/nodes/input/test_input_threading.py
  tests/pipeline/nodes/model/csrnetv1/test_csrnet.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
  tests/pipeline/nodes/model/hrnetv1/test_detector.py
  tests/pipeline/nodes/model/hrnetv1/test_hrnet.py
  tests/pipeline/nodes/model/hrnetv1/test_hrnet_model.py
  tests/pipeline/nodes/model/jdev1/test_jde.py
  tests/pipeline/nodes/model/movenetv1/test_movenet.py
  tests/pipeline/nodes/model/movenetv1/test_predictor.py
  tests/pipeline/nodes/model/mtcnnv1/test_mtcnn.py
  tests/pipeline/nodes/model/posenetv1/test_decode.py
  tests/pipeline/nodes/model/posenetv1/test_decode_multi.py
  tests/pipeline/nodes/model/posenetv1/test_detector.py
  tests/pipeline/nodes/model/posenetv1/test_posenet.py
  tests/pipeline/nodes/model/posenetv1/test_predictor.py
  tests/pipeline/nodes/model/posenetv1/test_preprocessing.py
  tests/pipeline/nodes/model/yolov4/test_yolo.py
  tests/pipeline/nodes/model/yolov4_face/test_yolo_face.py
  tests/pipeline/nodes/model/yolov4_license_plate/test_yolov4_license_plate.py
  tests/pipeline/nodes/model/yoloxv1/test_yolox.py
Labels: cicd

#578 Fix: failing cli create node tests on M1 Mac
  peekingduck/cli.py
  peekingduck/utils/create_node_helper.py
  tests/cli/test_cli_create_node.py
Labels: bug, testing

#579 Docs: remove extra click to node docs
  docs/_templates/class.rst
  docs/_templates/module.rst
  docs/source/data_type.rst
  docs/source/getting_started/02_configure_pkdk.md
  docs/source/getting_started/03_custom_nodes.md
  docs/source/getting_started/04_import_peekingduck.md
  docs/source/index.md
  docs/source/master.rst
  docs/source/use_cases/crowd_counting.md
  docs/source/use_cases/face_mask_detection.md
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/human_tracking.md
  docs/source/use_cases/multi_object_tracking.md
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/privacy_protection_faces.md
  docs/source/use_cases/privacy_protection_license_plate.md
  docs/source/use_cases/social_distancing.md
  docs/source/use_cases/zone_counting.md
Labels: documentation

#580 docs: shorten module names in sidebar
  .gitignore
  docs/Makefile
  docs/_templates/module.rst
  docs/source/conf.py
  docs/source/getting_started/03_custom_nodes.md
  docs/source/master.rst
  docs/source/use_cases/crowd_counting.md
  docs/source/use_cases/face_mask_detection.md
  docs/source/use_cases/human_tracking.md
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/privacy_protection_faces.md
  docs/source/use_cases/privacy_protection_license_plate.md
  docs/source/use_cases/zone_counting.md
Labels: documentation

#581 Docs: add glossary and faq page
  .github/workflows/pre_merge_ci.yml
  cicd_requirements.txt
  docs/_templates/class.rst
  docs/_templates/module.rst
  docs/source/data_type.rst
  docs/source/faq.rst
  docs/source/glossary.rst
  docs/source/master.rst
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  docs/source/resources/01c_object_tracking.rst
  docs/source/resources/01d_crowd_counting.rst
  peekingduck/pipeline/nodes/draw/bbox.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
  peekingduck/pipeline/nodes/draw/legend.py
  peekingduck/pipeline/nodes/draw/poses.py
  peekingduck/pipeline/nodes/draw/tag.py
  peekingduck/pipeline/nodes/draw/zones.py
  peekingduck/pipeline/nodes/input/live.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/pipeline/nodes/output/csv_writer.py
  peekingduck/pipeline/nodes/output/media_writer.py
Labels: documentation, cicd
