Repository aisingapore/PeekingDuck, pull requests merged in 2022-02, with the labels that each got.

#582 Docs: add explanation in node config template
  .github/workflows/pre_merge_ci.yml
  docs/source/glossary.rst
  peekingduck/configs/node_template.yml
Labels: documentation, cicd

#583 Docs: convert all docs files to RST
  README.md
  docs/source/getting_started/01_installation.md
  docs/source/getting_started/01_installation.rst
  docs/source/getting_started/02_configure_pkdk.md
  docs/source/getting_started/02_configure_pkdk.rst
  docs/source/getting_started/03_custom_nodes.md
  docs/source/getting_started/03_custom_nodes.rst
  docs/source/getting_started/04_import_peekingduck.md
  docs/source/getting_started/04_import_peekingduck.rst
  docs/source/getting_started/index.rst
  docs/source/index.md
  docs/source/index.rst
  docs/source/master.rst
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  docs/source/resources/01d_crowd_counting.rst
  docs/source/use_cases/crowd_counting.md
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.md
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.md
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/human_tracking.md
  docs/source/use_cases/human_tracking.rst
  docs/source/use_cases/index.rst
  docs/source/use_cases/multi_object_tracking.md
  docs/source/use_cases/multiple_object_tracking.rst
  docs/source/use_cases/object_counting.md
  docs/source/use_cases/object_counting.rst
  docs/source/use_cases/privacy_protection_faces.md
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plate.md
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.md
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.md
  docs/source/use_cases/zone_counting.rst
  peekingduck/pipeline/nodes/dabble/tracking.py
  peekingduck/pipeline/nodes/draw/bbox.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
Labels: documentation

#584 Docs: change to US Eng
  .github/actions/system-test/action.yaml
  .github/workflows/post_merge_checks.yml
  docs/source/_static/css/pkdk.css
  docs/source/use_cases/group_size_checking.rst
  peekingduck/cli.py
  peekingduck/configs/dabble/check_large_groups.yml
  peekingduck/configs/dabble/group_nearby_objs.yml
  peekingduck/configs/model/yolo_face.yml
  peekingduck/configs/output/csv_writer.yml
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/dabble/check_large_groups.py
  peekingduck/pipeline/nodes/dabble/group_nearby_objs.py
  peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/iou_tracker.py
  peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/opencv_tracker.py
  peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/utils.py
  peekingduck/pipeline/nodes/draw/utils/bbox.py
  peekingduck/pipeline/nodes/draw/utils/constants.py
  peekingduck/pipeline/nodes/input/utils/read.py
  peekingduck/pipeline/nodes/model/csrnet.py
  peekingduck/pipeline/nodes/model/efficientdet.py
  peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/initializers.py
  peekingduck/pipeline/nodes/model/hrnet.py
  peekingduck/pipeline/nodes/model/hrnetv1/hrnet_files/detector.py
  peekingduck/pipeline/nodes/model/hrnetv1/hrnet_files/preprocessing.py
  peekingduck/pipeline/nodes/model/hrnetv1/hrnet_model.py
  peekingduck/pipeline/nodes/model/jde.py
  peekingduck/pipeline/nodes/model/jdev1/__init__.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/darknet.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/kalman_filter.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/matching.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/network_blocks.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/track.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/tracker.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/utils.py
  peekingduck/pipeline/nodes/model/movenetv1/movenet_files/predictor.py
  peekingduck/pipeline/nodes/model/mtcnn.py
  peekingduck/pipeline/nodes/model/posenet.py
  peekingduck/pipeline/nodes/model/yolo.py
  peekingduck/pipeline/nodes/model/yolo_face.py
  peekingduck/pipeline/nodes/model/yolo_license_plate.py
  peekingduck/pipeline/nodes/model/yolox.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/utils.py
  peekingduck/pipeline/nodes/node.py
  tests/cli/test_cli.py
  tests/pipeline/nodes/dabble/test_check_large_groups.py
  tests/pipeline/nodes/dabble/test_group_nearby_objs.py
  tests/use_cases/systest_group_size_checking.yml
  use_cases/group_size_checking.yml
Labels: documentation, cicd

#585 Docs: display install instructions in tabs
  docs/source/_static/css/pkdk.css
  docs/source/getting_started/01_basic_install.rst
  docs/source/getting_started/01_prerequisites.rst
  docs/source/getting_started/02_advanced_install.rst
  docs/source/getting_started/02_basic_install.rst
  docs/source/getting_started/index.rst
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/human_tracking.rst
  docs/source/use_cases/multiple_object_tracking.rst
  docs/source/use_cases/object_counting.rst
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.rst
Labels: documentation

#586 cicd: enable pip cache in pre merge CI
  .github/workflows/pre_merge_ci.yml
Labels: cicd

#593 Docs: import PeekingDuck as module tutorial (script and notebook example)
  docs/_templates/module.rst
  docs/source/getting_started/01_convention.rst
  docs/source/getting_started/03_advanced_install.rst
  docs/source/tutorials/02_duck_confit.rst
  docs/source/tutorials/04_import_as_module.rst
  docs/source/tutorials/index.rst
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/human_tracking.rst
  docs/source/use_cases/multiple_object_tracking.rst
  docs/source/use_cases/object_counting.rst
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.rst
  notebooks/demo_import_peekingduck.ipynb
  peekingduck/cli.py
  peekingduck/pipeline/nodes/dabble/__init__.py
  peekingduck/pipeline/nodes/draw/__init__.py
  peekingduck/pipeline/nodes/input/__init__.py
  peekingduck/pipeline/nodes/model/__init__.py
  peekingduck/pipeline/nodes/output/__init__.py
  peekingduck/runner.py
  setup.cfg
Labels: documentation

#591 Docs: modify cpu fps for movenet and efficientdet
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
Labels: documentation

#594 Docs: modify cpu fps for yolo, mtcnn, and hrnet
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
Labels: documentation
