Repository aisingapore/PeekingDuck, pull requests merged in 2022-08, with the labels that each got.

#670 node: YolactEdge code for instance segmentation
  peekingduck/configs/model/yolact_edge.yml
  peekingduck/pipeline/nodes/model/master_map.yml
  peekingduck/pipeline/nodes/model/yolact_edge.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/LICENSE
  peekingduck/pipeline/nodes/model/yolact_edgev1/__init__.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/__init__.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/backbone.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/detector.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/model.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/utils.py
  peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_model.py
  tests/pipeline/nodes/model/yolact_edgev1/__init__.py
  tests/pipeline/nodes/model/yolact_edgev1/test_groundtruth.yml
  tests/pipeline/nodes/model/yolact_edgev1/test_yolact_edge.py
Labels: enhancement, testing

#680 Docs: Documentation for YolactEdge
  docs/source/conf.py
  docs/source/resources/01e_instance_segmentation.rst
  docs/source/resources/02_bibliography.rst
  peekingduck/pipeline/nodes/model/yolact_edge.py
Labels: documentation

#681 Feat: config type checking
  lint_requirements.txt
  peekingduck/configs/draw/group_bbox_and_tag.yml
  peekingduck/configs/draw/poses.yml
  peekingduck/configs/output/media_writer.yml
  peekingduck/pipeline/nodes/abstract_node.py
  peekingduck/pipeline/nodes/augment/brightness.py
  peekingduck/pipeline/nodes/augment/contrast.py
  peekingduck/pipeline/nodes/augment/undistort.py
  peekingduck/pipeline/nodes/dabble/bbox_to_3d_loc.py
  peekingduck/pipeline/nodes/dabble/camera_calibration.py
  peekingduck/pipeline/nodes/dabble/check_large_groups.py
  peekingduck/pipeline/nodes/dabble/check_nearby_objs.py
  peekingduck/pipeline/nodes/dabble/group_nearby_objs.py
  peekingduck/pipeline/nodes/dabble/keypoints_to_3d_loc.py
  peekingduck/pipeline/nodes/dabble/statistics.py
  peekingduck/pipeline/nodes/dabble/tracking.py
  peekingduck/pipeline/nodes/dabble/trackingv1/detection_tracker.py
  peekingduck/pipeline/nodes/dabble/zone_count.py
  peekingduck/pipeline/nodes/dabble/zoningv1/zone.py
  peekingduck/pipeline/nodes/draw/bbox.py
  peekingduck/pipeline/nodes/draw/blur_bbox.py
  peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
  peekingduck/pipeline/nodes/draw/legend.py
  peekingduck/pipeline/nodes/draw/mosaic_bbox.py
  peekingduck/pipeline/nodes/draw/tag.py
  peekingduck/pipeline/nodes/draw/utils/bbox.py
  peekingduck/pipeline/nodes/input/visual.py
  peekingduck/pipeline/nodes/model/csrnet.py
  peekingduck/pipeline/nodes/model/efficientdet.py
  peekingduck/pipeline/nodes/model/fairmot.py
  peekingduck/pipeline/nodes/model/hrnet.py
  peekingduck/pipeline/nodes/model/jde.py
  peekingduck/pipeline/nodes/model/movenet.py
  peekingduck/pipeline/nodes/model/mtcnn.py
  peekingduck/pipeline/nodes/model/posenet.py
  peekingduck/pipeline/nodes/model/yolo.py
  peekingduck/pipeline/nodes/model/yolo_face.py
  peekingduck/pipeline/nodes/model/yolo_license_plate.py
  peekingduck/pipeline/nodes/model/yolox.py
  peekingduck/pipeline/nodes/output/csv_writer.py
  peekingduck/pipeline/nodes/output/media_writer.py
  peekingduck/pipeline/nodes/output/screen.py
  requirements.txt
  setup.cfg
  tests/pipeline/nodes/dabble/test_camera_calibration.py
  tests/pipeline/nodes/dabble/test_tracking.py
  tests/pipeline/nodes/dabble/test_zone_count.py
  tests/pipeline/nodes/draw/test_tag.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
  tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
  tests/pipeline/nodes/model/mtcnnv1/test_mtcnn.py
  tests/pipeline/nodes/output/test_csv_writer.py
  tests/pipeline/nodes/output/test_media_writer.py
  tests/pipeline/nodes/test_node.py
Labels: enhancement

#684 Docs: aisingapore migration
  .github/workflows/assign_issue_to_project.yml
  CONTRIBUTING.md
  README.md
  docs/source/faq.rst
  docs/source/getting_started/03_custom_install.rst
  docs/source/index.rst
  docs/source/tutorials/01_hello_cv.rst
  docs/source/tutorials/05_calling_peekingduck_in_python.rst
  docs/source/use_cases/_template_use_case.rst
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/object_counting_over_time.rst
  docs/source/use_cases/object_counting_present.rst
  docs/source/use_cases/people_counting_over_time.rst
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.rst
  notebooks/calling_peekingduck_in_python.ipynb
  setup.cfg
Labels: documentation

#695 Docs: add typeguard to macOS install instructions
  docs/source/getting_started/03_custom_install.rst
Labels: documentation

#694 Fix: consistent pytest weights location
  tests/pipeline/nodes/base/test_weights_downloader_mixin.py
  tests/pipeline/nodes/dabble/test_camera_calibration.py
  tests/pipeline/nodes/model/csrnetv1/test_csrnet.py
  tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
  tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
  tests/pipeline/nodes/model/hrnetv1/test_hrnet.py
  tests/pipeline/nodes/model/jdev1/test_jde.py
  tests/pipeline/nodes/model/mask_rcnnv1/test_mask_rcnn.py
  tests/pipeline/nodes/model/movenetv1/test_movenet.py
  tests/pipeline/nodes/model/movenetv1/test_predictor.py
  tests/pipeline/nodes/model/mtcnnv1/test_mtcnn.py
  tests/pipeline/nodes/model/posenetv1/test_posenet.py
  tests/pipeline/nodes/model/posenetv1/test_predictor.py
  tests/pipeline/nodes/model/yolact_edgev1/test_yolact_edge.py
  tests/pipeline/nodes/model/yolov4/test_yolo.py
  tests/pipeline/nodes/model/yolov4_face/test_yolo_face.py
  tests/pipeline/nodes/model/yolov4_license_plate/test_yolov4_license_plate.py
  tests/pipeline/nodes/model/yoloxv1/test_yolox.py
Labels: testing

#696 Cicd: output screen test on xvfb
  .github/workflows/daily_drift_checks.yml
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
  .github/workflows/publish_pypi.yml
  .github/workflows/standup_bot.yml
  peekingduck/declarative_loader.py
  peekingduck/pipeline/nodes/output/screen.py
  peekingduck/viewer/viewer.py
  tests/pipeline/nodes/output/test_screen.py
Labels: cicd, testing

#698 Cicd: run post merge with xvfb
  .github/workflows/post_merge_checks.yml
  .github/workflows/publish_pypi.yml
Labels: cicd

#700 Cicd: remove discord standup workflow
  .github/workflows/standup_bot.yml
  scripts/trigger_standupbot.sh
  scripts/webhook_issues.py
Labels: cicd

#701 Feat: skip integrity check if offline
  peekingduck/pipeline/nodes/base.py
  peekingduck/pipeline/nodes/input/utils/preprocess.py
  peekingduck/pipeline/nodes/input/utils/read.py
  peekingduck/pipeline/nodes/input/visual.py
  tests/pipeline/nodes/base/test_weights_downloader_mixin.py
  tests/pipeline/nodes/draw/test_tag.py
  tests/pipeline/nodes/input/test_input_threading.py
  tests/pipeline/nodes/input/test_visual.py
Labels: enhancement
