Repository aisingapore/PeekingDuck, pull requests merged in 2022-03, with the labels that each got.

#598 Feat: Change run_config.yml to pipeline.yml
  CONTRIBUTING.md
  README.md
  __main__.py
  docs/source/getting_started/02_basic_install.rst
  docs/source/resources/01a_object_detection.rst
  docs/source/tutorials/01_hello_cv.rst
  docs/source/tutorials/02_duck_confit.rst
  docs/source/tutorials/03_duck_power.rst
  docs/source/tutorials/04_import_as_module.rst
  docs/source/use_cases/_template_use_case.rst
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/human_tracking.rst
  docs/source/use_cases/multiple_object_tracking.rst
  docs/source/use_cases/object_counting.rst
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.rst
  peekingduck/cli.py
  peekingduck/declarative_loader.py
  peekingduck/runner.py
  pipeline_config.yml
  tests/cli/test_cli.py
  tests/cli/test_cli_create_node.py
  tests/loaders/test_declarativeloader.py
  tests/pipeline/nodes/input/test_input_threading.py
  tests/runner/test_runner.py
Labels: documentation, enhancement

#599 Docs: update video links
  docs/source/getting_started/02_basic_install.rst
  docs/source/getting_started/03_advanced_install.rst
  docs/source/include/substitution.rst
  docs/source/resources/01c_object_tracking.rst
  docs/source/tutorials/01_hello_cv.rst
  docs/source/tutorials/02_duck_confit.rst
  docs/source/tutorials/03_duck_power.rst
  docs/source/tutorials/04_import_as_module.rst
  peekingduck/cli.py
  peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/opencv_tracker.py
  setup.cfg
Labels: documentation, enhancement, dependencies

#600 Docs: add show/code code toggle to examples
  docs/_templates/page.html
  docs/source/_static/css/pkdk.css
  docs/source/getting_started/01_convention.rst
  docs/source/getting_started/02_basic_install.rst
  docs/source/getting_started/03_advanced_install.rst
  docs/source/tutorials/01_hello_cv.rst
  docs/source/tutorials/02_duck_confit.rst
  docs/source/tutorials/03_duck_power.rst
  docs/source/tutorials/04_import_as_module.rst
  tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
Labels: documentation, cicd

#602 Feat: log optional requirements message at the end
  docs/source/tutorials/04_import_as_module.rst
  notebooks/demo_import_peekingduck.ipynb
  peekingduck/pipeline/nodes/dabble/__init__.py
  peekingduck/pipeline/nodes/draw/__init__.py
  peekingduck/pipeline/nodes/input/__init__.py
  peekingduck/pipeline/nodes/model/__init__.py
  peekingduck/pipeline/nodes/output/__init__.py
  peekingduck/runner.py
  peekingduck/utils/requirement_checker.py
  tests/utils/test_requirement_checker.py
Labels: documentation, enhancement

#604 Fix: initialize batch norm in YOLOX
  peekingduck/configs/model/yolox.yml
  peekingduck/pipeline/nodes/model/yolox.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/detector.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/model.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_model.py
  tests/pipeline/nodes/model/yoloxv1/test_groundtruth.yml
  tests/pipeline/nodes/model/yoloxv1/test_yolox.py
  tests/pipeline/nodes/model/yoloxv1/test_yolox.yml
Labels: bug

#607 Docs: update GitHub readme
  README.md
  docs/source/assets/getting_started/verify_install.gif
  docs/source/getting_started/02_basic_install.rst
  pipeline_config.yml
Labels: documentation

#606 Fix: Add bgr2rgb to efficientdet model and update docs on the new performance for efficientdet and HRNet
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  peekingduck/pipeline/nodes/model/efficientdet.py
Labels: bug, documentation

#609 Docs: use case gallery
  README.md
  docs/source/assets/use_cases/face_mask_detection.gif
  docs/source/assets/use_cases/group_size_checking.gif
  docs/source/assets/use_cases/multiple_object_tracking.gif
  docs/source/index.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/index.rst
  docs/source/use_cases/multiple_object_tracking.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  peekingduck/pipeline/nodes/dabble/statistics.py
  use_cases/multiple_object_tracking.yml
  use_cases/privacy_protection_license_plates.yml
Labels: documentation

#611 Docs: update "Import PeekingDuck as a module" tutorial
  docs/source/index.rst
  docs/source/tutorials/05_import_as_module.rst
  notebooks/demo_import_peekingduck.ipynb
  peekingduck/cli.py
  peekingduck/pipeline/nodes/model/yolov4_license_plate/licenseplate_files/detector.py
  tests/cli/test_cli.py
Labels: bug, documentation

#613 Docs: use sphinx glossary for PeekingDuck data types
  docs/source/faq.rst
  docs/source/glossary.rst
  docs/source/include/data_type.rst
  docs/source/index.rst
  docs/source/tutorials/03_custom_nodes.rst
  docs/source/tutorials/04_peaking_duck.rst
  peekingduck/pipeline/nodes/augment/brightness.py
  peekingduck/pipeline/nodes/augment/contrast.py
  peekingduck/pipeline/nodes/dabble/bbox_count.py
  peekingduck/pipeline/nodes/dabble/bbox_to_3d_loc.py
  peekingduck/pipeline/nodes/dabble/bbox_to_btm_midpoint.py
  peekingduck/pipeline/nodes/dabble/check_large_groups.py
  peekingduck/pipeline/nodes/dabble/check_nearby_objs.py
  peekingduck/pipeline/nodes/dabble/fps.py
  peekingduck/pipeline/nodes/dabble/group_nearby_objs.py
  peekingduck/pipeline/nodes/dabble/keypoints_to_3d_loc.py
  peekingduck/pipeline/nodes/dabble/statistics.py
  peekingduck/pipeline/nodes/dabble/tracking.py
  peekingduck/pipeline/nodes/dabble/zone_count.py
  peekingduck/pipeline/nodes/draw/__init__.py
  peekingduck/pipeline/nodes/draw/bbox.py
  peekingduck/pipeline/nodes/draw/blur_bbox.py
  peekingduck/pipeline/nodes/draw/btm_midpoint.py
  peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
  peekingduck/pipeline/nodes/draw/heat_map.py
  peekingduck/pipeline/nodes/draw/legend.py
  peekingduck/pipeline/nodes/draw/mosaic_bbox.py
  peekingduck/pipeline/nodes/draw/poses.py
  peekingduck/pipeline/nodes/draw/tag.py
  peekingduck/pipeline/nodes/draw/zones.py
  peekingduck/pipeline/nodes/input/live.py
  peekingduck/pipeline/nodes/input/recorded.py
  peekingduck/pipeline/nodes/model/csrnet.py
  peekingduck/pipeline/nodes/model/efficientdet.py
  peekingduck/pipeline/nodes/model/fairmot.py
  peekingduck/pipeline/nodes/model/hrnet.py
  peekingduck/pipeline/nodes/model/jde.py
  peekingduck/pipeline/nodes/model/movenet.py
  peekingduck/pipeline/nodes/model/mtcnn.py
  peekingduck/pipeline/nodes/model/posenet.py
  peekingduck/pipeline/nodes/model/yolo.py
  peekingduck/pipeline/nodes/model/yolo_face.py
  peekingduck/pipeline/nodes/model/yolo_license_plate.py
  peekingduck/pipeline/nodes/model/yolox.py
  peekingduck/pipeline/nodes/output/csv_writer.py
  peekingduck/pipeline/nodes/output/media_writer.py
  peekingduck/pipeline/nodes/output/screen.py
Labels: documentation

#610 Docs: add readme logo/banner
  README.md
  docs/source/assets/peekingduck.svg
Labels: documentation

#614 feat: change --verify_install to use tempfile and stream from GCP
  peekingduck/cli.py
  pipeline_config.yml
  tests/cli/test_cli.py
Labels: documentation

#617 Docs: Add bgr2rgb to yolov4 model; update yolov4 accuracy; add yolox accuracy
  docs/source/resources/01a_object_detection.rst
  peekingduck/pipeline/nodes/model/yolov4/yolo_files/detector.py
Labels: bug, documentation

#623 Docs: Correct benchmark errors and update test conditions
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  docs/source/resources/01c_object_tracking.rst
Labels: documentation

#624 Feat: consolidate bbox transforms
  peekingduck/pipeline/nodes/model/fairmotv1/fairmot_files/track.py
  peekingduck/pipeline/nodes/model/fairmotv1/fairmot_files/tracker.py
  peekingduck/pipeline/nodes/model/fairmotv1/fairmot_files/utils.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/track.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/tracker.py
  peekingduck/pipeline/nodes/model/jdev1/jde_files/utils.py
  peekingduck/pipeline/nodes/model/mtcnnv1/mtcnn_files/detector.py
  peekingduck/pipeline/nodes/model/mtcnnv1/mtcnn_model.py
  peekingduck/pipeline/nodes/model/yolov4/yolo_files/detector.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/detector.py
  peekingduck/pipeline/nodes/model/yoloxv1/yolox_files/utils.py
  peekingduck/pipeline/utils/bbox/transforms.py
  tests/pipeline/nodes/model/mtcnnv1/test_groundtruth.yml
  tests/pipeline/nodes/model/mtcnnv1/test_mtcnn.py
Labels: enhancement

#632 bugfix: `input.visual` converter error for `input.live`/`input.recorded`
  peekingduck/declarative_loader.py
Labels: bug

#633 bugfix: 'input.visual' converter left out 'source:0' config
  peekingduck/declarative_loader.py
Labels: bug

#635 Docs: Fix typos and grammar
  README.md
  docs/source/faq.rst
  docs/source/getting_started/02_standard_install.rst
  docs/source/include/data_type.rst
  docs/source/index.rst
  docs/source/resources/01a_object_detection.rst
  docs/source/resources/01b_pose_estimation.rst
  docs/source/resources/01c_object_tracking.rst
  docs/source/tutorials/02_duck_confit.rst
  docs/source/tutorials/03_custom_nodes.rst
  docs/source/tutorials/04_peaking_duck.rst
  docs/source/tutorials/05_calling_peekingduck_in_python.rst
  docs/source/tutorials/index.rst
  docs/source/use_cases/_template_use_case.rst
  docs/source/use_cases/crowd_counting.rst
  docs/source/use_cases/face_mask_detection.rst
  docs/source/use_cases/group_size_checking.rst
  docs/source/use_cases/object_counting_over_time.rst
  docs/source/use_cases/object_counting_present.rst
  docs/source/use_cases/people_counting_over_time.rst
  docs/source/use_cases/privacy_protection_faces.rst
  docs/source/use_cases/privacy_protection_license_plates.rst
  docs/source/use_cases/social_distancing.rst
  docs/source/use_cases/zone_counting.rst
  notebooks/calling_peekingduck_in_python.ipynb
  peekingduck/pipeline/nodes/augment/brightness.py
  peekingduck/pipeline/nodes/augment/contrast.py
  peekingduck/pipeline/nodes/input/visual.py
Labels: documentation

#637 Run threading unit test over multiple RTSP URLs instead of just one
  tests/pipeline/nodes/input/test_input_threading.py
Labels: cicd
