Repository aisingapore/PeekingDuck, pull requests merged in 2023-01, with the labels that each got.

#735 Fix: create ragged numpy array with dtype=object explicitly
  peekingduck/utils/pose/keypoint_handler.py
  tests/nodes/model/hrnetv1/test_hrnet.py
  tests/nodes/model/movenetv1/test_movenet.py
  tests/nodes/model/posenetv1/test_posenet.py
Labels: bug

#732 feat: allowing users to set the bounding box color and flag to toggle displaying confidence scores on bbox
  peekingduck/configs/draw/bbox.yml
  peekingduck/nodes/draw/bbox.py
  peekingduck/nodes/draw/group_bbox_and_tag.py
  peekingduck/nodes/draw/utils/bbox.py
  tests/nodes/draw/test_bbox.py
  use_cases/setting_bbox_color.yml
Labels: enhancement

#736 Feat: sort `peekingduck nodes` output
  peekingduck/commands/nodes.py
  tests/cli/test_nodes.py
Labels: enhancement

#740 Cicd: bump workflow python version
  .github/workflows/daily_drift_checks.yml
  .github/workflows/post_merge_checks.yml
  .github/workflows/pre_merge_ci.yml
  .github/workflows/publish_pypi.yml
  requirements.txt
  requirements_cicd.txt
  requirements_lint.txt
  setup.cfg
Labels: cicd, dependencies

#738 Fix: cast connections keypoint to float
  .github/workflows/weekly_system_test.yml
  peekingduck/nodes/draw/utils/general.py
  tests/nodes/draw/test_pose.py
Labels: bug, cicd

#737 Feat: remove deprecation handling for 2.0.0
  __main__.py
  peekingduck/commands/core.py
  peekingduck/declarative_loader.py
  peekingduck/nodes/abstract_node.py
  peekingduck/nodes/node.py
Labels: enhancement

#744 Test: early exit input threading test
  tests/nodes/input/test_input_threading.py
Labels: testing
